version: '3.4'

services:
  database:
    build:
        context: ./docker/postgreSQL
        dockerfile: Dockerfile
    ports:
     - "25432:5432"
  redis:
    image: "redis:6-alpine"
    restart: always
    ports:
     - "6379:6379"
  jaeger:
    image: "jaegertracing/all-in-one"
    restart: always
    environment:
     - "COLLECTOR_ZIPKIN_HTTP_PORT=9411"
    ports:
     - "5775:5775/udp"
     - "6831:6831/udp"
     - "6832:6832/udp"
     - "5778:5778"
     - "16686:16686"
     - "14268:14268"
     - "14250:14250"
     - "9411:9411"
  api:
    image: ${DOCKER_REGISTRY-}eglsitapi
    build:
      context: .
      dockerfile: ./src/backend/Hcqn.Api/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
