version: '3.4'

services:
  database:
    environment:
      POSTGRES_USER : sit
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB : sit3
  api:
    environment:
      - ConnectionStrings__SitDbConnection=Host=database;Port=5432;Database=sit3;Username=sit;Password=123456;Persist Security Info=True
      - ConnectionStrings__EventStoreDbConnection=Host=database;Port=5432;Database=sit3;Username=sit;Password=123456;Persist Security Info=True
      - Redis__ConnectionString=redis:6379
      - JAEGER_SERVICE_NAME=sit-3
      - JAEGER_AGENT_HOST=jaeger
    expose:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
